/**
 * data-testid da vitrine Next (Fase 5+) e fluxo comprador (Fase 6).
 */
export const store = {
  slugLayout: 'store-slug-layout',
  header: 'store-header',
  homeProductGrid: 'store-home-product-grid',
  homeProductCard: (id: number | string): string => `store-home-product-card-${id}`,
  homeBannerCarousel: 'store-home-banner-carousel',
  productDetail: 'store-product-detail',
  productGallery: 'store-product-gallery',
  productGalleryThumb: (id: number | string): string => `store-product-gallery-thumb-${id}`,
  productTitle: 'store-product-title',
  productPrice: 'store-product-price',
  productAddCartBtn: 'store-product-add-cart-btn',
  productQty: 'store-product-qty',
  productQtyInput: 'store-product-qty-input',
  productBuyNowBtn: 'store-product-buy-now-btn',
  productTrust: 'store-product-trust',
  productRelated: 'store-product-related',
  productVariantPicker: 'store-product-variant-picker',
  productVariant: (mockId: string): string => `store-product-variant-${mockId}`,
  cartTable: 'store-cart-table',
  cartItemRow: (id: number | string): string => `store-cart-item-row-${id}`,
  cartCheckoutBtn: 'store-cart-checkout-btn',
  /** Link carrinho na nav da vitrine (I5) — legado; preferir `headerCart`. */
  navCart: 'store-nav-cart',
  headerSearch: 'store-header-search',
  headerCart: 'store-header-cart',
  headerCartBadge: 'store-header-cart-badge',
  headerCategory: (id: number | string): string => `store-header-category-${id}`,
  addCartToast: 'store-add-cart-toast',
  homeFiltersBar: 'store-filters-bar',
  filtersSort: 'store-filters-sort',
  categoryPill: (id: number | string): string => `store-category-pill-${id}`,
  sectionViewAll: (id: number | string): string => `store-section-view-all-${id}`,
  /** Botão menu mobile no header da vitrine (I5). */
  headerMenu: 'store-header-menu',
  checkoutForm: 'store-checkout-form',
  checkoutPayment: (metodo: string): string => `store-checkout-payment-${metodo}`,
  checkoutPaymentTeste: 'store-checkout-payment-teste',
  checkoutSubmitBtn: 'store-checkout-submit-btn',
  checkoutSuccessMsg: 'store-checkout-success-msg',
  ordersTable: 'store-orders-table',
  orderRow: (id: number | string): string => `store-order-row-${id}`,
  productRating: 'store-product-rating',
  productReviews: 'store-product-reviews',
  productReviewForm: 'store-product-review-form',
  productReviewStar: (value: number): string => `store-product-review-star-${value}`,
  wishlistBtn: (productId: number | string): string => `store-wishlist-btn-${productId}`,
  wishlistPage: 'store-wishlist-page',
  headerWishlist: 'store-header-wishlist',
  headerWishlistBadge: 'store-header-wishlist-badge',
} as const;
